cabal-version:      3.0
name:               axiom
version:            0.1.0.0

common shared
  default-language: GHC2021
  ghc-options:      -Wall
  build-depends:    base, text

library
  import:           shared
  hs-source-dirs:   src
  exposed-modules:  Axiom.Parser, Axiom.Ast
  build-depends:    megaparsec, containers >= 0.7, base >= 4.14 && < 5, mtl >= 2.3.1, parser-combinators >= 1.3.1

executable axiom
  import:           shared
  hs-source-dirs:   app
  main-is:          Main.hs
  build-depends:    axiom, megaparsec

test-suite tests
  import:           shared
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Main.hs
  other-modules:    Axiom.ParserTest
  build-depends:    axiom, tasty, tasty-hunit, megaparsec, containers >= 0.7, mtl >= 2.3.1
